name: Build Job

on:
  workflow_call:
    inputs:
      node-modules-cache-key:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      # Build the application
      - run: pnpm build

      # Upload build output as an artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 1
