version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      timezone: America/Chicago
    package-manager: pnpm
    commit-message:
      prefix: '⬆️ '
    groups:
      # Patch updates across all dependencies
      patch:
        update-types:
          - patch

      # NestJS related packages
      nestjs:
        patterns:
          - '@nestjs/*'

      # Testing related packages
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'supertest'
          - '@types/supertest'

      # TypeScript and types
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'ts-*'

      # SWC related packages
      swc:
        patterns:
          - '@swc/*'
          - 'unplugin-swc'

      # Biome
      biome:
        patterns:
          - '@biomejs/*'

      # Core runtime dependencies
      core:
        patterns:
          - 'rxjs'
          - 'reflect-metadata'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: America/Chicago
    commit-message:
      prefix: '⬆️ '
