name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js and pnpm with caching'
inputs:
  install-dependencies:
    description: 'Install pnpm dependencies (true/false)'
    required: false
    default: 'true'
  pnpm-version:
    description: 'pnpm version override (default: read from .tool-versions)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Extract pnpm version from .tool-versions
      id: pnpm-version
      shell: bash
      run: |
        if [[ -n "${{ inputs.pnpm-version }}" ]]; then
          echo "Using pnpm version from input: ${{ inputs.pnpm-version }}"
          echo "version=${{ inputs.pnpm-version }}" >> $GITHUB_OUTPUT
        elif [[ -f .tool-versions ]]; then
          PNPM_VERSION=$(grep 'pnpm' .tool-versions | awk '{print $2}' || echo "")
          if [[ -n "$PNPM_VERSION" ]]; then
            echo "Using pnpm version from .tool-versions: $PNPM_VERSION"
            echo "version=$PNPM_VERSION" >> $GITHUB_OUTPUT
          else
            echo "pnpm version not found in .tool-versions, using latest"
            echo "version=latest" >> $GITHUB_OUTPUT
          fi
        else
          echo "No .tool-versions file found, using latest pnpm"
          echo "version=latest" >> $GITHUB_OUTPUT
        fi

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ steps.pnpm-version.outputs.version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install
