name: CI

on:
  - push
  - pull_request

permissions:
  contents: read
  packages: write

jobs:
  quality:
    name: Code Quality
    uses: ./.github/workflows/jobs/quality.yml
  build:
    name: Build
    uses: ./.github/workflows/jobs/build.yml
  test:
    name: Test
    uses: ./.github/workflows/jobs/test.yml

  docker:
    name: Docker Build and Push
    needs: [build, test]
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/jobs/docker.yml

  summary:
    name: Workflow Summary
    needs: [quality, build, test, docker]
    if: always() # Run even if previous jobs fail
    uses: ./.github/workflows/jobs/summary.yml
    with:
      quality-result: ${{ needs.quality.result }}
      build-result: ${{ needs.build.result }}
      test-result: ${{ needs.test.result }}
      docker-result: ${{ needs.docker.result }}
